### ISSUE TITLE
SHFBROOT and ComponentPath with NuGet in Azure DevOps

### ISSUE THREAD

**Issue by eriksorngard** [EWSoftware/SHFB#748]
Hello,

I am trying to move running SHBF to our Azure DevOps build pipeline, after running it locally for years, but have not been able to configure the SHFBROOT variable correctly.

I have installed the EWSoftware.SHBF and EWSoftware.SHBF.NETFramework packages in the .NET Framework project.

As the solution does not have a package folder when working locally with VS2019, I have not been able to come up with a valid SHFBROOT and ComponentPath. Just to see what happened, I also copied the two PackageReference items from the .NET framework project to the SHFB project.

So far, the .NET framework project builds as expected, after both the required packages have been installed by NuGet restore, before MSBuild throws an error because it has not found the SandcastleHelpFileBuilder.targets.

How can I determine what is the correct path to the targets file?

**Comment by tom-englert** [comment]
This is fixed in #720, however it looks like this has not been released yet

**Comment by EWSoftware** [comment]
The property file is in the core tools package and the .NET 4.8 version of the reflection data set package.  If you're using those, I assume it should work.

**Comment by eriksorngard** [comment]
Thank you for your help, though I still get the error "Error MSB4019: The imported project "D:\SandcastleHelpFileBuilder.targets" was not found."

Initially I did not fully realize the difference between use of Packages.config and PackageReference, and the lack of a packages folder is of course due to this being a solution with only PackageReference projects. I have removed the ComponentPath and SHFBROOT variables from the SHFB project file, and added two package references:

  <ItemGroup>
    <PackageReference Include="EWSoftware.SHFB" Version="2019.9.15" />
    <PackageReference Include="EWSoftware.SHFB.NETFramework" Version="4.8.0" />
  </ItemGroup>

These are the latest versions available, and included in the SHFB project file before the failing <Import Project="$(SHFBROOT)\SandcastleHelpFileBuilder.targets" /> line. Both packages are being installed, because of their inclusion i the .NET framework project.

Does the item group with PackageReference tags have to be located in a special place of the project file?

**Comment by eriksorngard** [comment]
I did manage to get SHFB working, but had to find out where the build pipeline is putting the packages, and reference them with SHFBROOT and ComponentPath:

```
<PropertyGroup>
 
 <ComponentPath>C:\Users\VssAdministrator\.nuget\packages\ewsoftware.shfb.netframework\4.8.0</ComponentPath>
</PropertyGroup>
<PropertyGroup>
  <SHFBROOT Condition=" '$(SHFBROOT)' == '' ">C:\Users\VssAdministrator\.nuget\packages\ewsoftware.shfb\2019.9.15\tools</SHFBROOT>
</PropertyGroup>
```

**Comment by tom-englert** [comment]
Just tried by my own - looks like SHFB projects do not support nuget packages at all. 
- Right click on a SHFB project shows "Manage Nuget Packages" disabled
- Nothing will be restored when manually adding a PackageReference

**Comment by EWSoftware** [comment]
As far as I know, that's always been the case.  The packages have to be in the documented project in the solution rather than the SHFB project itself.

**Comment by eriksorngard** [comment]
When using PackageReference, the packages are neither in the SHFB project nor the doumented .NET framework project. They are only referenced from the documented project, which requires the long paths in my previous message to tell the build pipeline and SHFB where things are.

**Comment by tom-englert** [comment]
@eriksorngard @EWSoftware There is a simple workaround to use the nuget packages directly, without hardcoding the path to the nuget packages:
Add a new project (e.g. `Documentation.build.csproj`) in the same directory as your `Documentation.shfb` project, with the following content:
```xml
<Project ToolsVersion="Current" DefaultTargets="Build" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  <Import Project="$(MSBuildExtensionsPath)\$(MSBuildToolsVersion)\Microsoft.Common.props" Condition="Exists('$(MSBuildExtensionsPath)\$(MSBuildToolsVersion)\Microsoft.Common.props')" />
  <PropertyGroup>
    <TargetFrameworkVersion>v4.6.2</TargetFrameworkVersion>
    <ProjectGuid>{45C2507A-D756-4383-AA29-145416FEF56C}</ProjectGuid>
  </PropertyGroup>
  <PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Debug|AnyCPU' ">
  </PropertyGroup>
  <PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Release|AnyCPU' ">
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="EWSoftware.SHFB" Version="2019.9.15" />
    <PackageReference Include="EWSoftware.SHFB.NETFramework" Version="4.8.0" />
  </ItemGroup>
  <Import Project="Documentation.shfbproj" />
</Project>
```

Now do not build `Documentation.shfb` but the `Documentation.build.csproj`.

**Comment by eriksorngard** [comment]
Thank you for suggesting the additional project file. Running locally in Visual Studio, this works, but in the build pipeline, I am now unfortunately back to the old error message: I build the csproj project, and the shfbproj project do not know where SandcastleHelpFileBuilder.targets is.

```
Project "d:\a\1\s\Transformation Messages.sln" (1) is building "d:\a\1\s\Documentation\Documentation.build.csproj" (4) on node 1 (default targets).
d:\a\1\s\Documentation\Documentation.shfbproj(134,3): error MSB4019: The imported project "D:\SandcastleHelpFileBuilder.targets" was not found. Confirm that the path in the <Import> declaration is correct, and that the file exists on disk.
```

**Comment by tom-englert** [comment]
I tried locally with MSBuild, after setting the SHFBROOT environment variable to empty, and it worked all fine, now referencing the .targets from the nuget package.
Maybe SHFBROOT on your build server is not initially empty?

**Comment by tom-englert** [comment]
It's a hen-egg problem - if the nugets haven't been restored, the .shfbproj can't be loaded, so restore fails, because the common targets are missing.
That should work:
```xml
<Project ToolsVersion="Current" DefaultTargets="Build" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  <Import Project="$(MSBuildExtensionsPath)\$(MSBuildToolsVersion)\Microsoft.Common.props" Condition="Exists('$(MSBuildExtensionsPath)\$(MSBuildToolsVersion)\Microsoft.Common.props')" />
  <PropertyGroup>
    <TargetFrameworkVersion>v4.6.2</TargetFrameworkVersion>
    <ProjectGuid>{45C2507A-D756-4383-AA29-145416FEF56C}</ProjectGuid>
  </PropertyGroup>
  <PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Debug|AnyCPU' ">
  </PropertyGroup>
  <PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Release|AnyCPU' ">
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="EWSoftware.SHFB" Version="2019.9.15" />
    <PackageReference Include="EWSoftware.SHFB.NETFramework" Version="4.8.0" />
  </ItemGroup>
  <Import Project="$(MSBuildToolsPath)\Microsoft.Common.targets" Condition="'$(MSBuildRestoreSessionId)' != ''"/>
  <Import Project="Documentation.shfbproj"  Condition="'$(MSBuildRestoreSessionId)' == ''"/>
</Project>
```

**Comment by tom-englert** [comment]
Finally looking at the differences between a .csproj and the .shfbproj, we can make the .shfbproj support nuget packages with these changes:
```xml
<?xml version="1.0" encoding="utf-8"?>
<Project DefaultTargets="Build" xmlns="http://schemas.microsoft.com/developer/msbuild/2003" ToolsVersion="14.0">
  <!-- Import the common props to support NuGet packages via PackageReference -->
  <Import Project="$(MSBuildExtensionsPath)\$(MSBuildToolsVersion)\Microsoft.Common.props" Condition="Exists('$(MSBuildExtensionsPath)\$(MSBuildToolsVersion)\Microsoft.Common.props')" />
  <PropertyGroup>
     <!-- A framework version is required for NuGet restore, can be any valid version -->
    <TargetFrameworkVersion>v4.6.2</TargetFrameworkVersion>
    <PublishableProject>false</PublishableProject>
...
  <ItemGroup>
    <PackageReference Include="EWSoftware.SHFB" Version="2019.9.15" />
    <PackageReference Include="EWSoftware.SHFB.NETFramework" Version="4.8.0" />
  </ItemGroup>
  <!-- Import the common build targets during NuGet restore, because $(SHFBROOT) is not set yet -->
  <Import Project="$(MSBuildToolsPath)\Microsoft.Common.targets" Condition="'$(MSBuildRestoreSessionId)' != ''"/>
  <!-- Import the SHFB build targets during build -->
  <Import Project="$(SHFBROOT)\SandcastleHelpFileBuilder.targets" Condition="'$(MSBuildRestoreSessionId)' == ''"/>
</Project>
```

This will make the extra c# project obsolete.

**Comment by eriksorngard** [comment]
Thank you for your effort in making this work. Putting everything inside the shfbproj file would be the optimal solution. Unfortunately, it still does not work in our Azure DevOps pipeline, which still produces the same error message:

`\Documentation.shfbproj(184,3): Error MSB4019: The imported project "D:\SandcastleHelpFileBuilder.targets" was not found. Confirm that the path in the <Import> declaration is correct, and that the file exists on disk.`

There are no references to SHFBROOT in the solution elsewhere that I can find, but somehow MSBuild always looks at "D:\" for some reason.

Since the documented project also reference the two SHFB packages, I have also tried to remove them from here, in case there was some interference, but with no change.

**Comment by tom-englert** [comment]
This works great here: 
https://ci.appveyor.com/project/tom-englert/tomstoolbox
https://github.com/tom-englert/TomsToolbox/blob/master/appveyor.yml
https://github.com/tom-englert/TomsToolbox/blob/master/Documentation/Documentation.shfbproj

- What VS-Version do you use?
- How do you restore your nuget packages?

**Comment by NIBShura** [comment]
I ran into same problem.

@tom-englert - do you have Sandcastle Help File Builder installed on your build machine?

**Comment by tom-englert** [comment]
Not in the AppVeyor environment. If you look at the build output, you can see that it's using the NuGet package.

**Comment by tom-englert** [comment]
You can test locally by setting shfbroot empty and then call msbuild

**Comment by eriksorngard** [comment]
I have done another attempt on this today, and was able to run SHFB locally with these modifications, after removing the SHFBROOT environment variable and performing a package restore. However, I took a good look at the build pipeline logs and find this message:

`d:\a\1\s\Documentation\Documentation.shfbproj : warning NU1503: Skipping restore for project 'd:\a\1\s\Documentation\Documentation.shfbproj'. The project file may be invalid or missing targets required for restore. [C:\Users\VssAdministrator\AppData\Local\Temp\NuGetScratch\bfklkjeq.0t5.nugetinputs.targets]`

The .shfbproj file is apparently valid enough when I run msbuild locally.

**Comment by DerekGn** [comment]
For anyone scratching their head on this one after making the changes to the .shfbproj as mentioned here https://github.com/EWSoftware/SHFB/issues/748#issuecomment-546717383

The problem is down to how the azure build pipeline is configured.

If you use the Nuget restore task to restore the packages it will not successfully restore the packages for the .shfbproj

>Starting: NuGet restore
==============================================================================
Task         : NuGet
Description  : Restore, pack, or push NuGet packages, or run a NuGet command. Supports NuGet.org and authenticated feeds like Azure Artifacts and MyGet. Uses NuGet.exe and works with .NET Framework apps. For .NET Core and .NET Standard apps, use the .NET Core task.
Version      : 2.171.1
Author       : Microsoft Corporation
Help         : https://docs.microsoft.com/azure/devops/pipelines/tasks/package/nuget
==============================================================================
SYSTEMVSSCONNECTION exists true
SYSTEMVSSCONNECTION exists true
C:\windows\system32\chcp.com 65001
Active code page: 65001
Detected NuGet version 4.4.1.4656 / 4.4.1
SYSTEMVSSCONNECTION exists true
C:\hostedtoolcache\windows\NuGet\4.4.1\x64\nuget.exe sources Add -NonInteractive -Name NuGetOrg -Source https://api.nuget.org/v3/index.json -ConfigFile D:\a\1\Nuget\tempNuGet_101.config
Package Source with Name: NuGetOrg added successfully.
C:\hostedtoolcache\windows\NuGet\4.4.1\x64\nuget.exe restore D:\a\1\s\Sdk.sln -Verbosity Detailed -NonInteractive -ConfigFile D:\a\1\Nuget\tempNuGet_101.config
NuGet Version: 4.4.1.4656
MSBuild auto-detection: using msbuild version '15.9.21.664' from 'C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\15.0\bin'. Use option -MSBuildVersion to force nuget to use a specific version of MSBuild.
MSBuild P2P timeout [ms]: 120000
C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\15.0\bin\msbuild.exe "C:\Users\VssAdministrator\AppData\Local\Temp\NuGetScratch\2ubzlpdu.mkj.nugetinputs.targets" /t:GenerateRestoreGraphFile /nologo /nr:false /v:q /p:NuGetRestoreTargets="C:\Users\VssAdministrator\AppData\Local\Temp\NuGetScratch\4w2leo52.yjk.nugetrestore.targets" /p:RestoreTaskAssemblyFile="C:\hostedtoolcache\windows\NuGet\4.4.1\x64\nuget.exe" /p:RestoreSolutionDirectory="D:\a\1\s" /p:RestoreConfigFile="D:\a\1\Nuget\tempNuGet_101.config" /p:SolutionDir="D:\a\1\s"
D:\a\1\s\Sdk.Docs\Sdk.Docs.shfbproj(126,3): error MSB4019: The imported project "D:\SandcastleHelpFileBuilder.targets" was not found. Confirm that the path in the <Import> declaration is correct, and that the file exists on disk.
D:\a\1\s\Sdk.Docs\Sdk.Docs.shfbproj : warning NU1503: Skipping restore for project 'D:\a\1\s\Sdk.Docs\Sdk.Docs.shfbproj'. The project file may be invalid or missing targets required for restore. [C:\Users\VssAdministrator\AppData\Local\Temp\NuGetScratch\2ubzlpdu.mkj.nugetinputs.targets]

Using the Visual Studio Build Task will also fail to build the .shfproj

##[error]Eko.Sdk.Docs\Eko.Sdk.Docs.shfbproj(126,3): Error MSB4019: The imported project "D:\SandcastleHelpFileBuilder.targets" was not found. Confirm that the path in the <Import> declaration is correct, and that the file exists on disk.
Project "D:\a\1\s\Eko.Sdk.Docs\Eko.Sdk.Docs.shfbproj.metaproj" (7) is building "D:\a\1\s\Eko.Sdk.Docs\Eko.Sdk.Docs.shfbproj" (9) on node 1 (default targets).

Using the Azure Devops pipeline MsBuild Task to build the shfproj will compile the documentation without issue. I passed the -restore argument to the Msbuild Task.

>Starting: Build solution Sdk.Docs/Sdk.Docs.shfbproj
==============================================================================
Task         : MSBuild
Description  : Build with MSBuild
  Assets file has not changed. Skipping assets file writing. Path: D:\a\1\s\Sdk.Docs\obj\project.assets.json
  Restore completed in 64.44 ms for D:\a\1\s\Sdk.Docs\Sdk.Docs.shfbproj.
  
  >NuGet Config files used:
      C:\Users\VssAdministrator\AppData\Roaming\NuGet\NuGet.Config
      C:\Program Files (x86)\NuGet\Config\Microsoft.VisualStudio.Offline.config
  
>  Feeds used:
      https://api.nuget.org/v3/index.json
      C:\Program Files (x86)\Microsoft SDKs\NuGetPackages\
Done Building Project "D:\a\1\s\Sdk.Docs\Sdk.Docs.shfbproj" (Restore target(s)).
Project "D:\a\1\s\Sdk.Docs\Sdk.Docs.shfbproj" on node 1 (default targets).
CoreBuildHelp:
  Building D:\a\1\s\Sdk.Docs\Sdk.Docs.shfbproj
  Initializing
  ValidatingDocumentationSources
  GenerateSharedContent
  GenerateApiFilter
  GenerateReflectionInfo
  TransformReflectionInfo
  GenerateNamespaceSummaries
  GenerateInheritedDocumentation
  CopyConceptualContent
  CreateConceptualTopicConfigs
  CopyAdditionalContent
  MergeTablesOfContents
  GenerateIntermediateTableOfContents
  CreateBuildAssemblerConfigs
  MergeCustomConfigs
  BuildTopics

**Comment by avivanoff** [comment]
[This solution](https://github.com/EWSoftware/SHFB/issues/812#issuecomment-681308974) worked for me.

**Comment by capricorn-15** [comment]
Just as a hint: The WiX Toolset (https://wixtoolset.org/) is able to use PackageReference with their own project files:

Here is my project which is working fine on our build server:

![image](https://github.com/EWSoftware/SHFB/assets/146751283/a3c921e7-d563-4d6e-84ed-6d27a323b3a2)

It would be really great if we could use it for SHFB like this.

[Sample.zip](https://github.com/EWSoftware/SHFB/files/12783972/Sample.zip)
